import { v4 as uuid } from 'uuid';

const seedColors = [
  {
    paletteName: 'Material UI Colors',
    id: 'material-ui-colors',
    emoji: '🎨',
    colors: [
      { id: uuid(), name: 'red', color: '#F44336' },
      { id: uuid(), name: 'pink', color: '#E91E63' },
      { id: uuid(), name: 'purple', color: '#9C27B0' },
      { id: uuid(), name: 'deeppurple', color: '#673AB7' },
      { id: uuid(), name: 'indigo', color: '#3F51B5' },
      { id: uuid(), name: 'blue', color: '#2196F3' },
      { id: uuid(), name: 'lightblue', color: '#03A9F4' },
      { id: uuid(), name: 'cyan', color: '#00BCD4' },
      { id: uuid(), name: 'teal', color: '#009688' },
      { id: uuid(), name: 'green', color: '#4CAF50' },
      { id: uuid(), name: 'lightgreen', color: '#8BC34A' },
      { id: uuid(), name: 'lime', color: '#CDDC39' },
      { id: uuid(), name: 'yellow', color: '#FFEB3B' },
      { id: uuid(), name: 'amber', color: '#FFC107' },
      { id: uuid(), name: 'orange', color: '#FF9800' },
      { id: uuid(), name: 'deeporange', color: '#FF5722' },
      { id: uuid(), name: 'brown', color: '#795548' },
      { id: uuid(), name: 'grey', color: '#9E9E9E' },
      { id: uuid(), name: 'bluegrey', color: '#607D8B' },
    ],
  },
  {
    paletteName: 'Flat UI Colors v1',
    id: 'flat-ui-colors-v1',
    emoji: '🤙',
    colors: [
      { id: uuid(), name: 'Turquoise', color: '#1abc9c' },
      { id: uuid(), name: 'Emerald', color: '#2ecc71' },
      { id: uuid(), name: 'PeterRiver', color: '#3498db' },
      { id: uuid(), name: 'Amethyst', color: '#9b59b6' },
      { id: uuid(), name: 'WetAsphalt', color: '#34495e' },
      { id: uuid(), name: 'GreenSea', color: '#16a085' },
      { id: uuid(), name: 'Nephritis', color: '#27ae60' },
      { id: uuid(), name: 'BelizeHole', color: '#2980b9' },
      { id: uuid(), name: 'Wisteria', color: '#8e44ad' },
      { id: uuid(), name: 'MidnightBlue', color: '#2c3e50' },
      { id: uuid(), name: 'SunFlower', color: '#f1c40f' },
      { id: uuid(), name: 'Carrot', color: '#e67e22' },
      { id: uuid(), name: 'Alizarin', color: '#e74c3c' },
      { id: uuid(), name: 'Clouds', color: '#ecf0f1' },
      { id: uuid(), name: 'Concrete', color: '#95a5a6' },
      { id: uuid(), name: 'Orange', color: '#f39c12' },
      { id: uuid(), name: 'Pumpkin', color: '#d35400' },
      { id: uuid(), name: 'Pomegranate', color: '#c0392b' },
      { id: uuid(), name: 'Silver', color: '#bdc3c7' },
      { id: uuid(), name: 'Asbestos', color: '#7f8c8d' },
    ],
  },
  {
    paletteName: 'Flat UI Colors Dutch',
    id: 'flat-ui-colors-dutch',
    emoji: '🇳🇱',
    colors: [
      { id: uuid(), name: 'Sunflower', color: '#FFC312' },
      { id: uuid(), name: 'Energos', color: '#C4E538' },
      { id: uuid(), name: 'BlueMartina', color: '#12CBC4' },
      { id: uuid(), name: 'LavenderRose', color: '#FDA7DF' },
      { id: uuid(), name: 'BaraRose', color: '#ED4C67' },
      { id: uuid(), name: 'RadiantYellow', color: '#F79F1F' },
      { id: uuid(), name: 'AndroidGreen', color: '#A3CB38' },
      { id: uuid(), name: 'MediterraneanSea', color: '#1289A7' },
      { id: uuid(), name: 'LavenderTea', color: '#D980FA' },
      { id: uuid(), name: 'VerryBerry', color: '#B53471' },
      { id: uuid(), name: 'PuffinsBill', color: '#EE5A24' },
      { id: uuid(), name: 'PixelatedGrass', color: '#009432' },
      { id: uuid(), name: 'MerchantMarineBlue', color: '#0652DD' },
      { id: uuid(), name: 'ForgottenPurple', color: '#9980FA' },
      { id: uuid(), name: 'HollyHock', color: '#833471' },
      { id: uuid(), name: 'RedPigment', color: '#EA2027' },
      { id: uuid(), name: 'TurkishAqua', color: '#006266' },
      {
        id: uuid(),
        name: '20000LeaguesUnderTheSea',
        color: '#1B1464',
      },
      { id: uuid(), name: 'CircumorbitalRing', color: '#5758BB' },
      { id: uuid(), name: 'MagentaPurple', color: '#6F1E51' },
    ],
  },
  {
    paletteName: 'Flat UI Colors American',
    id: 'flat-ui-colors-american',
    emoji: '🇺🇸',
    colors: [
      { id: uuid(), name: 'LightGreenishBlue', color: '#55efc4' },
      { id: uuid(), name: 'FadedPoster', color: '#81ecec' },
      { id: uuid(), name: 'GreenDarnerTail', color: '#74b9ff' },
      { id: uuid(), name: 'ShyMoment', color: '#a29bfe' },
      { id: uuid(), name: 'CityLights', color: '#dfe6e9' },
      { id: uuid(), name: 'MintLeaf', color: '#00b894' },
      { id: uuid(), name: 'RobinsEggBlue', color: '#00cec9' },
      { id: uuid(), name: 'ElectronBlue', color: '#0984e3' },
      { id: uuid(), name: 'ExodusFruit', color: '#6c5ce7' },
      { id: uuid(), name: 'SoothingBreeze', color: '#b2bec3' },
      { id: uuid(), name: 'SourLemon', color: '#ffeaa7' },
      { id: uuid(), name: 'FirstDate', color: '#fab1a0' },
      { id: uuid(), name: 'PinkGlamour', color: '#ff7675' },
      { id: uuid(), name: 'Pico8Pink', color: '#fd79a8' },
      { id: uuid(), name: 'AmericanRiver', color: '#636e72' },
      { id: uuid(), name: 'BrightYarrow', color: '#fdcb6e' },
      { id: uuid(), name: 'OrangeVille', color: '#e17055' },
      { id: uuid(), name: 'Chi-Gong', color: '#d63031' },
      { id: uuid(), name: 'PrunusAvium', color: '#e84393' },
      { id: uuid(), name: 'DraculaOrchid', color: '#2d3436' },
    ],
  },
  {
    paletteName: 'Flat UI Colors Aussie',
    id: 'flat-ui-colors-aussie',
    emoji: '🇦🇺',
    colors: [
      { id: uuid(), name: 'Beekeeper', color: '#f6e58d' },
      { id: uuid(), name: 'SpicedNectarine', color: '#ffbe76' },
      { id: uuid(), name: 'PinkGlamour', color: '#ff7979' },
      { id: uuid(), name: 'JuneBud', color: '#badc58' },
      { id: uuid(), name: 'CoastalBreeze', color: '#dff9fb' },
      { id: uuid(), name: 'Turbo', color: '#f9ca24' },
      { id: uuid(), name: 'QuinceJelly', color: '#f0932b' },
      { id: uuid(), name: 'CarminePink', color: '#eb4d4b' },
      { id: uuid(), name: 'PureApple', color: '#6ab04c' },
      { id: uuid(), name: 'HintOfIcePack', color: '#c7ecee' },
      { id: uuid(), name: 'MiddleBlue', color: '#7ed6df' },
      { id: uuid(), name: 'Heliotrope', color: '#e056fd' },
      { id: uuid(), name: 'ExodusFruit', color: '#686de0' },
      { id: uuid(), name: 'DeepKoamaru', color: '#30336b' },
      { id: uuid(), name: 'SoaringEagle', color: '#95afc0' },
      { id: uuid(), name: 'GreenlandGreen', color: '#22a6b3' },
      { id: uuid(), name: 'SteelPink', color: '#be2edd' },
      { id: uuid(), name: 'Blurple', color: '#4834d4' },
      { id: uuid(), name: 'DeepCove', color: '#130f40' },
      { id: uuid(), name: 'WizardGrey', color: '#535c68' },
    ],
  },
  {
    paletteName: 'Flat UI Colors British',
    id: 'flat-ui-colors-british',
    emoji: '🇬🇧',
    colors: [
      { id: uuid(), name: 'ProtossPylon', color: '#00a8ff' },
      { id: uuid(), name: 'Periwinkle', color: '#9c88ff' },
      { id: uuid(), name: 'Rise-N-Shine', color: '#fbc531' },
      { id: uuid(), name: 'DownloadProgress', color: '#4cd137' },
      { id: uuid(), name: 'Seabrook', color: '#487eb0' },
      { id: uuid(), name: 'VanaDylBlue', color: '#0097e6' },
      { id: uuid(), name: 'MattPurple', color: '#8c7ae6' },
      { id: uuid(), name: 'NanohanachaGold', color: '#e1b12c' },
      { id: uuid(), name: 'SkirretGreen', color: '#44bd32' },
      { id: uuid(), name: 'Naval', color: '#40739e' },
      { id: uuid(), name: 'NasturcianFlower', color: '#e84118' },
      { id: uuid(), name: 'LynxWhite', color: '#f5f6fa' },
      { id: uuid(), name: 'BlueberrySoda', color: '#7f8fa6' },
      { id: uuid(), name: 'MazarineBlue', color: '#273c75' },
      { id: uuid(), name: 'BlueNights', color: '#353b48' },
      { id: uuid(), name: 'HarleyOrange', color: '#c23616' },
      { id: uuid(), name: 'HintOfPensive', color: '#dcdde1' },
      { id: uuid(), name: 'ChainGangGrey', color: '#718093' },
      { id: uuid(), name: 'PicoVoid', color: '#192a56' },
      { id: uuid(), name: 'ElectroMagnetic', color: '#2f3640' },
    ],
  },
  {
    paletteName: 'Flat UI Colors Spanish',
    id: 'flat-ui-colors-spanish',
    emoji: '🇪🇸',
    colors: [
      { id: uuid(), name: 'JacksonsPurple', color: '#40407a' },
      { id: uuid(), name: 'C64Purple', color: '#706fd3' },
      { id: uuid(), name: 'SwanWhite', color: '#f7f1e3' },
      { id: uuid(), name: 'SummerSky', color: '#34ace0' },
      { id: uuid(), name: 'CelestialGreen', color: '#33d9b2' },
      { id: uuid(), name: 'LuckyPoint', color: '#2c2c54' },
      { id: uuid(), name: 'Liberty', color: '#474787' },
      { id: uuid(), name: 'HotStone', color: '#aaa69d' },
      { id: uuid(), name: 'DevilBlue', color: '#227093' },
      { id: uuid(), name: 'PalmSpringsSplash', color: '#218c74' },
      { id: uuid(), name: 'FlourescentRed', color: '#ff5252' },
      { id: uuid(), name: 'SyntheticPumpkin', color: '#ff793f' },
      { id: uuid(), name: 'CrocodileTooth', color: '#d1ccc0' },
      { id: uuid(), name: 'MandarinSorbet', color: '#ffb142' },
      { id: uuid(), name: 'SpicedButterNut', color: '#ffda79' },
      { id: uuid(), name: 'EyeOfNewt', color: '#b33939' },
      { id: uuid(), name: 'ChileanFire', color: '#cd6133' },
      { id: uuid(), name: 'GreyPorcelain', color: '#84817a' },
      { id: uuid(), name: 'AlamedaOchre', color: '#cc8e35' },
      { id: uuid(), name: 'Desert', color: '#ccae62' },
    ],
  },
  {
    paletteName: 'Flat UI Colors Indian',
    id: 'flat-ui-colors-indian',
    emoji: '🇮🇳',
    colors: [
      { id: uuid(), name: 'OrchidOrange', color: '#FEA47F' },
      { id: uuid(), name: 'SpiroDiscoBall', color: '#25CCF7' },
      { id: uuid(), name: 'HoneyGlow', color: '#EAB543' },
      { id: uuid(), name: 'SweetGarden', color: '#55E6C1' },
      { id: uuid(), name: 'FallingStar', color: '#CAD3C8' },
      { id: uuid(), name: 'RichGardenia', color: '#F97F51' },
      { id: uuid(), name: 'ClearChill', color: '#1B9CFC' },
      { id: uuid(), name: 'WhitePepper', color: '#F8EFBA' },
      { id: uuid(), name: 'Keppel', color: '#58B19F' },
      { id: uuid(), name: 'ShipsOfficer', color: '#2C3A47' },
      { id: uuid(), name: 'FieryFuchsia', color: '#B33771' },
      { id: uuid(), name: 'BlueBell', color: '#3B3B98' },
      { id: uuid(), name: 'GeorgiaPeach', color: '#FD7272' },
      { id: uuid(), name: 'OasisStream', color: '#9AECDB' },
      { id: uuid(), name: 'BrightUbe', color: '#D6A2E8' },
      { id: uuid(), name: 'MagentaPurple', color: '#6D214F' },
      { id: uuid(), name: 'EndingNavyBlue', color: '#182C61' },
      { id: uuid(), name: 'SasquatchSocks', color: '#FC427B' },
      { id: uuid(), name: 'PineGlade', color: '#BDC581' },
      { id: uuid(), name: 'HighlighterLavender', color: '#82589F' },
    ],
  },
  {
    paletteName: 'Flat UI Colors French',
    id: 'flat-ui-colors-french',
    emoji: '🇫🇷',
    colors: [
      { id: uuid(), name: 'FlatFlesh', color: '#fad390' },
      { id: uuid(), name: 'MelonMelody', color: '#f8c291' },
      { id: uuid(), name: 'Livid', color: '#6a89cc' },
      { id: uuid(), name: 'Spray', color: '#82ccdd' },
      { id: uuid(), name: 'ParadiseGreen', color: '#b8e994' },
      { id: uuid(), name: 'SquashBlossom', color: '#f6b93b' },
      { id: uuid(), name: 'MandarinRed', color: '#e55039' },
      { id: uuid(), name: 'AzraqBlue', color: '#4a69bd' },
      { id: uuid(), name: 'Dupain', color: '#60a3bc' },
      { id: uuid(), name: 'AuroraGreen', color: '#78e08f' },
      { id: uuid(), name: 'IcelandPoppy', color: '#fa983a' },
      { id: uuid(), name: 'TomatoRed', color: '#eb2f06' },
      { id: uuid(), name: 'YueGuangBlue', color: '#1e3799' },
      { id: uuid(), name: 'GoodSamaritan', color: '#3c6382' },
      { id: uuid(), name: 'Waterfall', color: '#38ada9' },
      { id: uuid(), name: 'CarrotOrange', color: '#e58e26' },
      { id: uuid(), name: 'JalapenoRed', color: '#b71540' },
      { id: uuid(), name: 'DarkSapphire', color: '#0c2461' },
      { id: uuid(), name: 'ForestBlues', color: '#0a3d62' },
      { id: uuid(), name: 'ReefEncounter', color: '#079992' },
    ],
  },
];

export default seedColors;
